// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMdcyfv_inX9D76A4O2MAq8CXiBthWuh4',
    appId: '1:441950659902:web:e628dac12e92565fe3f86f',
    messagingSenderId: '441950659902',
    projectId: 'clean-arch-example',
    authDomain: 'clean-arch-example.firebaseapp.com',
    storageBucket: 'clean-arch-example.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ7jZSVMPGbCA8e7hPscBOSvF6XrpvuM4',
    appId: '1:441950659902:android:1a07f276b721bc3ae3f86f',
    messagingSenderId: '441950659902',
    projectId: 'clean-arch-example',
    storageBucket: 'clean-arch-example.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMdcyfv_inX9D76A4O2MAq8CXiBthWuh4',
    appId: '1:441950659902:web:a998920a752425c6e3f86f',
    messagingSenderId: '441950659902',
    projectId: 'clean-arch-example',
    authDomain: 'clean-arch-example.firebaseapp.com',
    storageBucket: 'clean-arch-example.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMdS0xsmQFf9kN3xaU6h6phuxSE6lj6FA',
    appId: '1:441950659902:ios:e13a457509e120cbe3f86f',
    messagingSenderId: '441950659902',
    projectId: 'clean-arch-example',
    storageBucket: 'clean-arch-example.firebasestorage.app',
    iosBundleId: 'com.example.cleanarchexample',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMdS0xsmQFf9kN3xaU6h6phuxSE6lj6FA',
    appId: '1:441950659902:ios:e13a457509e120cbe3f86f',
    messagingSenderId: '441950659902',
    projectId: 'clean-arch-example',
    storageBucket: 'clean-arch-example.firebasestorage.app',
    iosBundleId: 'com.example.cleanarchexample',
  );

}